spring.application.name=cloudStorage
#spring.mvc.servlet.path=/api

logging.level.org.springframework.security=DEBUG

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_storage
spring.datasource.password=cloud_password
spring.datasource.username=cloud_user

#??? ???? ????? ???????? ???????? ? orm ????? ?? ?????? ?? ????? ??
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.properties.hibernate.hbm2ddl.auto=validate
#spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#spring.session.store-type=jdbc
#spring.session.jdbc.initialize-schema=always
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public